//This file defines all the action types to be used in various actions and reducers

export const AddUserToStore = "USER.ADDUSERTOSTORE";
export const AddProductToStore = "PRODUCT.ADDPRODUCTTOSTORE";

//Product Action Types
export const ADD_PRODUCTS_TOSTORE = "PRODUCT.ADD_PRODUCTS_TOSTORE";
export const FETCH_PRODUCTS_FULFILLED = "PRODUCT.FETCH_PRODUCTS_FULFILLED";
export const FETCH_PRODUCTS_REJECTED = "PRODUCT.FETCH_PRODUCTS_REJECTED";

//For Cart //action types for cart operations
export const ADD_ITEM = "CART.ADD_ITEM";
export const REMOVE_ITEM = "CART.REMOVE_ITEM";
export const UPDATE_ITEM = "CART.UPDATE_ITEM";
export const EMPTY_CART = "CART.EMPTY_CART";
export const REORDER_ITEM = "CART.REORDER_ITEM";

//For Coupon
export const ADD_COUPONS = "COUPON.ADD_COUPONS";

//For recent orders
//export const UPDATE_RECENT_ORDERS = "ORDERS.UPDATE_RECENT_ORDERS";
//export const REMOVE_RECENT_ORDER = "ORDERS.REMOVE_RECENT_ORDER";
export const ADD_RECENT_ORDER = "ORDERS.ADD_RECENT_ORDER";
export const GET_RECENT_ORDERS_SUCCESS = "ORDERS.GET_RECENT_ORDERS_SUCCESS";
export const GET_RECENT_ORDERS_FAILED = "ORDERS.GET_RECENT_ORDERS_FAILED";
export const CANCEL_ORDER_SUCCESS = "ORDERS.CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILED = "ORDERS.CANCEL_ORDER_FAILED";
export const GET_CANCELLED_ORDERS_SUCCESS = "ORDERS.GET_CANCELLED_ORDERS_SUCCESS";
export const GET_CANCELLED_ORDERS_FAILED = "ORDERS.GET_CANCELLED_ORDERS_FAILED";
export const REMOVE_ORDER = "ORDERS.REMOVE_ORDER";
export const UPDATE_STATUS = "ORDERS.UPDATE_STATUS";

//For Review
export const ADD_REVIEW = "REVIEWS.ADD_REVIEW";
export const GET_REVIEWS_SUCCESS = "REVIEWS.GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILED = "REVIEWS.GET_REVIEWS_FAILED";
export const SAVE_REVIEW = "REVIEWS.SAVE_REVIEW";
export const UPDATE_REVIEW = "REVIEWS.UPDATE_REVIEW";

//For Notification
export const ADD_NOTIFICATION = "NOTIFICATION.ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "NOTIFICATION.REMOVE_NOTIFICATION";
export const UPDATE_DYNAMIC_NOTIFICATION = "NOTIFICATION.UPDATE_DYNAMIC_NOTIFICATION";












